sudo: required
laguage: node_js
node_js:
  - "9"
  - "10"
  - "node"
services:
  - docker
before_script:
  - sudo /etc/init.d/mysql stop
before_install:
  - cp .env.dist .env
  - docker-compose up -d --build --force-recreate
  - npm i -g npm@latest
  - npm i -g yarn
install:
  - yarn
script:
  - yarn run test
after_success: yarn run coveralls